#!/bin/sh
# Create UCI config section required by form.Map
touch /etc/config/dae
uci -q get dae.settings >/dev/null || {
    uci set dae.settings=settings
    uci commit dae
}
mkdir -p /etc/dae
[ -f /etc/dae/config.dae ] && chmod 600 /etc/dae/config.dae
exit 0
